[global]
mraauthor=["jotego"]
platform="jtkiwi"

[features]
beta = true
# debug = true

[parse]
sourcefile="tnzs.cpp"
skip = { setnames = [
# MCU not supported
"extrmatn",
"extrmatnj",
"extrmatnu",
"extrmatnur",

"arknoid2",
"arknoid2j",
"arknoid2u",
"chukatai",
"chukataij",
"chukataija",
"chukataiu",
"drtoppel",
"drtoppelj",
"drtoppelu",
# "kabukiz",
# "kabukizj",
# "kageki",
# "kagekih",
# "kagekij",
# "kagekiu",
"plumppop",

# "tnzs",
# "tnzsj",
"tnzsjo",
"tnzso",
"tnzsoa",
"tnzsop",
"tnzsuo",
# Korean hack on mostly unrelated hardware
"jpopnics",
 ] }

 [header]
 len=$JTFRAME_HEADER
 data=[
    { machine="extrmatn", data="03" }, # MCU - Color PROM
    { machine="kabukiz",  data="04" }, # Kabuki Z sound subsystem
    { machine="kageki" ,  data="08" }, # Kageki   sound subsystem
 ]

[buttons]
core=$JTFRAME_BUTTONS
Names = [ { machine="insectx", names="Fire,Warp"},
          { machine="kageki", names="Left jab,Right hook"} ]

[dipsw]
bitcnt = 16
delete = [ "Unused", "Unknown" ]

[ROM]
regions = [
    { name="maincpu", No_offset=true   },
    { name="sub", start=$JTFRAME_BA1_START },
    { name="audiocpu", start=$JTFRAME_BA2_START },
    { name="samples", start=$PCM_START },
    { name="gfx1", start=$JTFRAME_BA3_START, width=32, No_offset=true, sort_reverse=true },
    { machine="kageki", name="gfx1", start=$JTFRAME_BA3_START, width=32, No_offset=true, regex_sort= [
            "7a", "13a", "4a", "10a",
            "5a", "12a", "\\.2a", "8a"
        ] },
    { machine="insectx", name="gfx1", start=$JTFRAME_BA3_START, width=16, No_offset=true },
    { name="proms", start=$JTFRAME_PROM_START, No_offset=true },
    { name="mcu", start=$MCU_START, No_offset=true   },
    { name="pal", skip=true },
]

order = [
    "maincpu", "sub", "audiocpu", "samples",
    "gfx1", "proms", "mcu"
]


