[global]
mraauthor=["jotego"]
platform="jtkiwi"

[features]
beta = true
# debug = true

[parse]
sourcefile="tnzs.cpp"
skip = { setnames = [
# "extrmatn",
# "extrmatnj",
# "extrmatnu",
# "extrmatnur",

"arknoid2",
"arknoid2j",
"arknoid2u",
"chukatai",
"chukataij",
"chukataija",
"chukataiu",
"drtoppel",
"drtoppelj",
"drtoppelu",
"jpopnics",
"kabukiz",
"kabukizj",
"kageki",
"kagekih",
"kagekij",
"kagekiu",
"plumppop",
"tnzs",
"tnzsj",
"tnzsjo",
"tnzso",
"tnzsoa",
"tnzsop",
"tnzsuo"
 ] }

[buttons]
core=$JTFRAME_BUTTONS
Names = [ { machine="insectx", names="Fire,Warp"} ]

[dipsw]
bitcnt = 16
delete = [ "Unused", "Unknown" ]

[ROM]
regions = [
    { name="maincpu", No_offset=true   },
    { name="sub", start=$JTFRAME_BA1_START },
    { name="audiocpu", start=$JTFRAME_BA2_START },
    { name="samples", start=$PCM_START },
    { name="gfx1", start=$JTFRAME_BA3_START, width=32, No_offset=true, sort_reverse=true },
    { machine="insectx", name="gfx1", start=$JTFRAME_BA3_START, width=16, No_offset=true },
    { name="proms", start=$JTFRAME_PROM_START, No_offset=true },
    { name="mcu", start=$MCU_START, No_offset=true   },
    { name="pal", skip=true },
]

order = [
    "maincpu", "sub", "audiocpu", "samples",
    "gfx1", "proms", "mcu"
]


